### ISSUE TITLE
Meta: v1.2

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/Booster#109]
Tracking progress towards Booster V1.2. AFAICT, the critical issues are:
- [ ] Figure out what's wrong with all the v1.0 and v1.1 boards that don't work and fix them. This would kill two birds with one stone as fixing the broken Booster v1.0 would give us another 8 channels of RF, which would be a great help!
- [x] Decide what we're going to do about the reverse power interlock https://github.com/sinara-hw/Booster/issues/83
- [x] Make sure we've understood and fixed the I2C issues https://github.com/sinara-hw/Booster/issues/76
- [ ] Understand how mechanical stress on one of the modules was able to take down the entire chassis. Was one pin shorting or something? Was this an issue with a supply pin or an I2C pin (or an I2C shorting to a supply or something like that)? This may be related to the fact that one channel on one of our Boosters wasn't detected until the lid was put on, which changed the mechanical stress

The rest are small issues which have obvious fixes (see the v1.2 milestone).

@gkasprow what do you think the timeline for production of v1.2 will be?
